# Generated by Django 4.2.2 on 2023-06-16 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('fee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedetails',
            name='regNo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student'),
        ),
    ]
