# Generated by Django 4.2.2 on 2023-06-17 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('fee', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeeDetails',
            new_name='FeeDetail',
        ),
    ]
