# Generated by Django 4.2.2 on 2023-06-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0003_rename_feedetails_feedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedetail',
            name='paymentDate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
