# Generated by Django 4.2.2 on 2023-11-22 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0004_feedetail_paymentdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedetail',
            old_name='duiNo',
            new_name='referenceNumber',
        ),
        migrations.RenameField(
            model_name='feedetail',
            old_name='regNo',
            new_name='registerNumber',
        ),
    ]
